### ISSUE TITLE
recipe for target 'ommstuf.o' failed

### ISSUE THREAD

**Issue by BelyaevaJuly** [marcodelapierre/tinker-openmm-plumed#1]
Good afternoon, dear colleague,

I am trying to install tinker-openmm-plumed. All requirements have been installed, files from ./tinker-openmm-plumed/ were putted to ~/tinker/source directory. Makefile were a little bit edited. So, when I run "make" an error occurs:

ommstuf.cpp: In function ‘void openmm_init_(void**, double*)’:
ommstuf.cpp:4181:39: error: ‘OpenMM_PropertyArray_create’ was not declared in this scope
    OpenMM_PropertyArray* properties = OpenMM_PropertyArray_create ();
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4181:39: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray* properties = OpenMM_PropertyArray_create ();
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       OpenMM_PropertyArray_get
ommstuf.cpp:4182:4: error: ‘OpenMM_PropertyArray_add’ was not declared in this scope
    OpenMM_PropertyArray_add (properties, "DisablePmeStream", "true");
    ^~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4182:4: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray_add (properties, "DisablePmeStream", "true");
    ^~~~~~~~~~~~~~~~~~~~~~~~
    OpenMM_PropertyArray_get
ommstuf.cpp:4185:4: error: ‘OpenMM_PropertyArray_destroy’ was not declared in this scope
    OpenMM_PropertyArray_destroy (properties);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4185:4: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray_destroy (properties);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    OpenMM_PropertyArray_get
ommstuf.cpp:4188:70: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘void*’ [-Wformat=]
       (void) fprintf (log, "\n OpenMMDataHandle:  %x\n", (void*)(omm));
                                                          ~~~~~~~~~~~~^
ommstuf.cpp:4189:76: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘void*’ [-Wformat=]
       (void) fprintf (log, "\n Integrator:  %x\n", (void*)(omm->integrator));
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~^
ommstuf.cpp: In function ‘int openmm_test_()’:
ommstuf.cpp:4941:39: error: ‘OpenMM_PropertyArray_create’ was not declared in this scope
    OpenMM_PropertyArray* properties = OpenMM_PropertyArray_create ();
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4941:39: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray* properties = OpenMM_PropertyArray_create ();
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       OpenMM_PropertyArray_get
ommstuf.cpp:4942:4: error: ‘OpenMM_PropertyArray_add’ was not declared in this scope
    OpenMM_PropertyArray_add (properties, "DisablePmeStream", "true");
    ^~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4942:4: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray_add (properties, "DisablePmeStream", "true");
    ^~~~~~~~~~~~~~~~~~~~~~~~
    OpenMM_PropertyArray_get
ommstuf.cpp:4945:4: error: ‘OpenMM_PropertyArray_destroy’ was not declared in this scope
    OpenMM_PropertyArray_destroy (properties);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
ommstuf.cpp:4945:4: note: suggested alternative: ‘OpenMM_PropertyArray_get’
    OpenMM_PropertyArray_destroy (properties);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    OpenMM_PropertyArray_get
Makefile:735: recipe for target 'ommstuf.o' failed
make: *** [ommstuf.o] Error 1

______
What could I do to finish installation?

**Comment by marcodelapierre** [comment]
Hi, this project is currently stalled with no ETA for completion, and therefore the installation is not expected to work in this current form.

I had put a message on the repo title, but I have now updated the README, too, to make the status clearer.

Apologies for any inconvenience.
Marco
